name: Requirements Check

runs:
  using: "composite"
  steps:
    - name: Check if requirements.txt exists
      run: |
        if [ ! -f requirements.txt ]; then
          echo "requirements.txt not found!"
          exit 1
        fi
      shell: bash

    - name: Install dependencies
      run: pip install -r requirements.txt
      shell: bash