name: Deployment

runs:
  using: "composite"
    
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t "deploymentaction:latest" .
      shell: bash

    - name: Push Docker image to Docker Hub
      run:  docker push "deploymentaction:latest"
      shell: bash