name: Maintenance

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install pip-tools for dependency checks
      run: |
        python -m pip install --upgrade pip
        pip install pip-review
    shell: bash

    - name: Check for outdated dependencies
      run: |
        echo "Checking for outdated dependencies..."
        pip-review --local
    shell: bash