name: Cancel Queued Workflows

on:
  push:
    branches: ["master"]

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Queued Workflows
        uses: actions/github-script@v6
        with:
          script: |
            const { data: workflows } = await github.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              status: 'in_progress',
            });

            for (const run of workflows.workflow_runs) {
              if (run.conclusion === null) {  // Indicates it's queued
                await github.actions.cancelWorkflowRun({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  run_id: run.id,
                });
                console.log(`Canceled workflow run: ${run.id}`);
              }
            }
