name: Format Code

on:
  push:
    branches: ["master"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install flake8 black

      - name: Run Flake8 Linting
        run: flake8 src/

      - name: Run Black Formatting Check
        run: black --check src/
