name: Debugging

on:
  push:
    branches: ["master"]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint bandit pytest pytest-html

      - name: Run pylint
        run: |
          pylint **/*.py > src/reports/pylint_report.txt

      - name: Run Bandit Security Check
        run:  bandit -r . -f json -o src/reports/bandit_report.json 

  tests:
    runs-on: ubuntu-latest
    # needs: linting

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-html

      - name: Run pytest
        run:  pytest -v --html=src/reports/pytest_report.html --self-contained-html