name: Python Tests

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  setup:
   uses: ./.github/workflows/setup.yml

  test_create_book:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run test_create_book
      run: pytest -v -k "test_create_book"

  test_get_book:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run test_get_book
        run: pytest -v -k "test_get_book"

  test_update_book:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run test_update_book
        run: pytest -v -k "test_update_book"

  test_delete_book:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run test_delete_book
        run: pytest -v -k "test_delete_book"

  test_get_all_books:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Run test_get_all_books
        run: pytest -v -k "test_get_all_books"