name: Python Tests

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      python-cache: ${{ steps.cache-python.outputs.cache-hit }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cache dependencies
        id: cache-python
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-v2

  test_create_book:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run test_create_book
      run: pytest -v -k "test_create_book"

  test_get_book:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run test_get_book
        run: pytest -v -k "test_get_book"

  test_update_book:
    runs-on: ubuntu-latest
    needs: test_get_book

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run test_update_book
        run: pytest -v -k "test_update_book"

  test_delete_book:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run test_delete_book
        run: pytest -v -k "test_delete_book"

  test_get_all_books:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Run test_get_all_books
        run: pytest -v -k "test_get_all_books"