name: Data Backup

on:
  schedule:
    - cron: '0 */23 * * *'
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  backup-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Commit Backup
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          mkdir -p backups
          cp resources/book_list.json backups/book_list_$(date +%F_%H-%M-%S).json
          git add backups/book_list_$(date +%F_%H-%M-%S).json
          git commit -m "Backup of book_list.json on $(date +%F %H:%M:%S)"
          git push
