name: SDLC Workflow

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    
jobs:
  sdlc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Requirements
        uses: ./.github/actions/requirements

      - name: Design Verification
        uses: ./.github/actions/design

      - name: Implementation
        uses: ./.github/actions/implementation

      - name: Testing
        uses: ./.github/actions/testing

      - name: Deployment
        uses: ./.github/actions/deployment

      - name: Maintenance
        uses: ./.github/actions/maintenance

