name: Update dependencies

on:
  push:
    branches: ["master"]
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 1"  # every Monday at 2 AM

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up python 
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install pip-tools
      run:  pip install pip-tools

    - name: Commit and push changes
      run: |
        pip-compile --upgrade
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add requirements.txt
        git commit -m "Update dependencies"
        git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
